class LoginPageLocators:
    USERNAME = 'username'
    PASSWORD = 'password'
    LOGIN_BUTTON = 'input[value="Login"]'
    STAFF_MENU = '[data-test-id="staff-menu"]'
    LOGOUT_BUTTON = '[data-test-id="staff-menu_logout"]'

class TicketPageLocators:
    TITLE_BAR = '[data-test-id="current-module"]'
    SETTINGS = 'li[data-test-id*="manage-{}"] a'
    ALL_TICKETS = 'li[title="All Tickets"] a'
    GLOBAL_SEARCH = '[data-test-id="global-search"]'
    SEARCH_INPUT = 'input[type="search"]'
    TEST_TICKET = '[data-test-id="tickets-table"] a[title="{}"]'
    TEST_TICKET_PRIORITY = '[data-test-id="ticket-box_priority"]'
    TEST_TICKET_STATUS = '[data-test-id="ticket-box_status"]'
    REPLY = '[data-test-id="reply-link"]'
    CANNED_ACTION_DROP_DOWN_BOX = '[data-test-id="canned-action-trigger"]'
    CANNED_ACTIONS = 'ul[id*="select-options"] li'
    CANNED_ACTION_APPLY_BUTTON = '[data-test-id*="add-canned-action"]'
    ADD_REPLY_BUTTON = '[data-test-id="add-update-reply-button"]'
    LATEST_TICKET_UPDATES = '(//article[@data-test-id="ticket-update"])[1]/ul/li'
    EXPAND_TICKET_UPDATES = '[data-test-id="updates-section_expand-all"]'

class StatusPageLocators:
    TITLE_BAR = '[data-test-id="current-module"]'
    MODULE = 'div[data-test-id*="{}"]'
    NEW_STATUS_BUTTON = '[data-test-id="new-status"]'
    STATUS_NAME_INPUT = 'input[aria-label="Status Name"]'
    STATUS_DESCRIPTION_INPUT = 'textarea[aria-label="Description"]'
    ADD_STATUS_BUTTON = '[data-test-id="add-status"]'
    TEST_STATUS = '//div[@data-test-id="statuses-table"]//div[@title="{}"]/ancestor::tr'
    DELETE_STATUS_BUTTON = '[data-test-id*="status-delete"]'
    DELETE_STATUS_CONFIRM_BUTTON = 'button[data-test-id*="delete"]'
    MAKE_DEFAULT_LINK = TEST_STATUS + '//td[contains(@class, "no-padding")]'
    STATUS_DROP_DOWN_BOX = '//div[contains(@class,"confirmation-dialog")]//div[@class="ember-basic-dropdown"]'
    CLOSING_STATUS_OPTION = '(//div[contains(@class,"confirmation-dialog")]//div[@class="ember-basic-dropdown"]//li)[1]'
    STATUS_BEHAVIOUR = '[data-test-id="form-field-behavior"]'
    STATUS_BEHAVIOUR_OPTIONS = STATUS_BEHAVIOUR + ' ul li'
    DEFAULT_STATUS_TICK = TEST_STATUS + '//div[@data-test-id="default-status"]'
    TOAST_MESSAGE = '[data-test-id=toast-message-close] > svg'

class PriorityPageLocators:
    TITLE_BAR = '[data-test-id="current-module"]'
    MODULE = 'div[data-test-id*="{}"] a'
    NEW_PRIORITY_BUTTON = '[data-test-id="new-priority"]'
    PRIORITY_NAME_INPUT = 'input[aria-label="Priority Name"]'
    PRIORITY_DESCRIPTION_INPUT = 'textarea[aria-label="Description"]'
    ADD_PRIOTIY_BUTTON = 'button[data-test-id="add-priority"]'
    TEST_PRIORITY = '//span[@title="{}"]/ancestor::tr'
    MAKE_DEFAULT_LINK = TEST_PRIORITY + '//td[contains(@class, "no-padding")]'
    DEFAULT_PRIORITY_TICK = TEST_PRIORITY + '//div[@data-test-id="default-priority"]'
    DELETE_PRIORITY_LINK = 'a[data-test-id*="priority-delete"]'
    PRIORITY_DROP_DOWN_BOX = '//div[contains(@class,"confirmation-dialog")]//div[@class="ember-basic-dropdown"]'
    CLOSING_PRIORITY_OPTION = '(//div[contains(@class,"confirmation-dialog")]//div[@class="ember-basic-dropdown"]//li)[1]'
    DELETE_PRIORITY_CONFIRMATION_BUTTON = '//button[contains(@data-test-id, "delete") and contains(@class,"confirmation")]'
    TOAST_MESSAGE = '[data-test-id=toast-message-close] > svg'

class SupportCenterPageLocators:
    TICKET_SUBJECT_INPUT = '[id="id_subject"]'
    TICKET_MESSAGE_INPUT = '[role="textbox"]'
    FILE_ATTACHMENT_BOX = 'input[id="attach-file-input"]'
    ATTACHED_FILE = '[class="hf-attach-file_name"]'
    CUSTOMER_NAME_INPUT = 'input[id="id_name"]'
    CUSTOMER_EMAIL_INPUT = 'input[id="id_email"]'
    CREATE_TICKET_BUTTON = 'button[id="submit"]'